# Generated by Django 5.2.1 on 2025-06-03 08:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên Danh Mục')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Mô Tả')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True, verbose_name='Slug')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày Tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày Cập Nhật')),
                ('is_active', models.BooleanField(default=True, verbose_name='Kích Hoạt')),
            ],
            options={
                'verbose_name': 'Danh Mục',
                'verbose_name_plural': 'Danh Mục',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Tên Sách')),
                ('author', models.CharField(max_length=100, verbose_name='Tác Giả')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True)),
                ('description', models.TextField(verbose_name='Mô Tả')),
                ('price', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Giá')),
                ('stock', models.IntegerField(verbose_name='Số Lượng Tồn Kho')),
                ('image', models.ImageField(blank=True, null=True, upload_to='books/', verbose_name='Hình Ảnh')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='books.category', verbose_name='Thể Loại')),
            ],
            options={
                'verbose_name': 'Sách',
                'verbose_name_plural': 'Sách',
                'ordering': ['title'],
            },
        ),
    ]
