# Generated by Django 5.2.1 on 2025-06-08 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_discount_percentage_alter_book_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Nhập phần trăm giảm giá (0-100)', max_digits=5, verbose_name='Phần trăm giảm giá (%)'),
        ),
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Giá'),
        ),
    ]
