# Generated by Django 5.2.1 on 2025-06-08 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_book_discount_percentage_alter_book_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='discount_percentage',
        ),
        migrations.AddField(
            model_name='book',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Giảm Giá (%)'),
        ),
    ]
