# Generated by Django 5.2.1 on 2025-06-08 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_city_alter_order_district_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Ghi chú'),
        ),
    ]
